name: Build and push docker image to Docker Hub

on:
  workflow_run:
    workflows: ['Build, test and push coverage']
    types:
      - completed
    branches: ['main']

permissions:
  packages: write
  contents: write
  attestations: write
  id-token: write

jobs:
  run:
    uses: ./.github/workflows/build-and-push-container_reusable.yml
    with:
      version: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      MOCKAPIC_DISPATCH_EVENT: ${{ secrets.MOCKAPIC_DISPATCH_EVENT }}