name: Build test and coverage (reusable)

on:
  workflow_call:
    inputs:
      coverage:
        required: true
        type: boolean
    secrets:
      codecov:

jobs:
  build_test_coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -race -covermode=atomic -coverprofile=coverage.out

    - name: Upload coverage to Codecov
      if: ${{ inputs.coverage }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.codecov }} # required
        verbose: true # optional (default = false)

    - name: Check vulnerabilities
      uses: golang/govulncheck-action@v1
      with:
        go-version-input: 1.23.4
        go-package: ./...
