name: Publish new container image tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define the tag version (x.x.x)'
        required: true
        type: string

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  build_docker:
    uses: ./.github/workflows/build-and-push-container_reusable.yml
    with:
      version: ${{ inputs.version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      MOCKAPIC_DISPATCH_EVENT: ${{ secrets.MOCKAPIC_DISPATCH_EVENT }}